INSERT INTO SERVICE(SVC_NAME,SVC_TIME, SVC_COST)
VALUES ('Nails', 60, 20.00);

INSERT INTO SERVICE(SVC_NAME, SVC_TIME, SVC_COST)
VALUES ('Hair Color', 120, 35.00);

INSERT INTO STYLIST(S_FNAME, S_LNAME, S_USERNAME, S_PASSWORD, S_SPECIALTY, S_EARNINGS)
VALUES ('Debbie', 'Pettis', 'DPettis', 'P@ssw0rd.1', 1, 0);

INSERT INTO CLIENT(C_FNAME, C_LNAME, C_USERNAME, C_PASSWORD, C_MAINSTYLIST)
VALUES('Melanie', 'Pettis', 'MPettis', 'P@ssw0rd.1', 'DPettis');

INSERT INTO APPOINTMENT(A_STYLIST, A_CLIENT, A_SERVICE, A_TIME)
VALUES('DPettis', 'MPettis', 2, '2017-11-10 12:00:00');
