DROP TABLE SERVICE IF EXISTS;
CREATE MEMORY TABLE SERVICE(
  SVC_ID        INT NOT NULL AUTO_INCREMENT,
  SVC_NAME      VARCHAR_IGNORECASE(255) NOT NULL,
  SVC_TIME      INT NOT NULL, -- TIME IN MINUTES
  SVC_COST      DECIMAL(4, 2) NOT NULL,
  PRIMARY KEY (SVC_ID)
);

DROP TABLE STYLIST IF EXISTS;
CREATE MEMORY TABLE STYLIST(
  S_FNAME       VARCHAR_IGNORECASE(255) NOT NULL,
  S_LNAME       VARCHAR_IGNORECASE(255) NOT NULL,
  S_USERNAME    VARCHAR_IGNORECASE(255) NOT NULL,
  S_PASSWORD    VARCHAR_IGNORECASE(255) NOT NULL,
  S_SPECIALTY   INT NOT NULL,
  S_EARNINGS    INT NOT NULL,
  PRIMARY KEY (S_USERNAME),
  FOREIGN KEY (S_SPECIALTY) REFERENCES SERVICE
);

DROP TABLE CLIENT IF EXISTS;
CREATE MEMORY TABLE CLIENT(
  C_FNAME       VARCHAR_IGNORECASE(255) NOT NULL,
  C_LNAME       VARCHAR_IGNORECASE(255) NOT NULL,
  C_USERNAME    VARCHAR_IGNORECASE(255) NOT NULL,
  C_PASSWORD    VARCHAR_IGNORECASE(255),
  C_MAINSTYLIST VARCHAR_IGNORECASE(255),
  PRIMARY KEY (C_USERNAME),
  FOREIGN KEY (C_MAINSTYLIST) REFERENCES STYLIST
);

DROP TABLE APPOINTMENT IF EXISTS;
CREATE MEMORY TABLE APPOINTMENT(
  A_ID          INT NOT NULL AUTO_INCREMENT,
  A_STYLIST     VARCHAR_IGNORECASE(255) NOT NULL,
  A_CLIENT      VARCHAR_IGNORECASE(255) NOT NULL,
  A_SERVICE     INT NOT NULL,
  A_TIME        DATETIME NOT NULL,
  PRIMARY KEY (A_ID),
  FOREIGN KEY (A_STYLIST) REFERENCES STYLIST,
  FOREIGN KEY (A_CLIENT) REFERENCES CLIENT,
  FOREIGN KEY (A_SERVICE) REFERENCES SERVICE
);